### ISSUE TITLE
request for docs

### ISSUE THREAD

**Issue by MareoRaft** [peteward44/rhinoify#3]
Could you provide an example of how to use this transform with Browserify?

Currently, the readme shows how to use it without Browserify only.

**Comment by MareoRaft** [comment]
something like

    browserify main.js -t rhinoify -o bundle.js

or

    browserify main.js -t rhinoify --standalone test -o bundle.js

worked for me, and would do nicely on the README.

**Comment by peteward44** [comment]
I've added to the README, thankyou :+1:
